//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForms.Classes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assembly
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assembly()
        {
            this.AssemblyProperties = new HashSet<AssemblyProperty>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int FK_Customer { get; set; }
        public int FK_Factory { get; set; }
        public bool Active { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Factory Factory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyProperty> AssemblyProperties { get; set; }
    }
}
